# Importing Libraries

In [56]:
#Import libraries
import pandas as pd
import numpy as np
import os

# Importing Data

In [57]:
#Imported path
path = r'/Users/racheldurand/Desktop/Data Analytics/Achievement 4/Instacart Basket Analysis RD'

In [58]:
path

'/Users/racheldurand/Desktop/Data Analytics/Achievement 4/Instacart Basket Analysis RD'

In [59]:
#Imported orders.csv
df_ords = pd.read_csv(os.path.join(path,'02 Data', 'Original Data', 'orders.csv'), index_col = False)

In [60]:
#Imported orders_wrangled.csv
df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv'), index_col = False)

In [61]:
#Imported df_prods.csv
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'products.csv'), index_col = False)

# Consistency Checks

# Products Consistency Check

In [62]:
#Step 2
df_prods.describe()

product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

My observations of the statistics are that max value for prices seems high at 99999.000000.

In [63]:
#Step 3 and 4
for col in df_prods.columns.tolist():
  weird = (df_prods[[col]].applymap(type) != df_prods[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_prods[weird]) > 0:
    print (col)

product_name


Product name has mixed-type data (and will be addressed).

In [64]:
#Step 5
#Checking for missing values in prods
df_prods.isnull().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

16 missing values in the product_name column.

In [65]:
#Step 6
# Addressing the misssing values
df_nan = df_prods[df_prods['product_name'].isnull()== True]

In [66]:
df_nan

product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14    12.2
68             69          NaN        26              7    11.8
115           116          NaN        93              3    10.8
261           262          NaN       110             13    12.1
525           525          NaN       109             11     1.2
1511         1511          NaN        84             16    14.3
1780         1780          NaN       126             11    12.3
2240         2240          NaN        52              1    14.2
2586         2586          NaN       104             13    12.4
3159         3159          NaN       126             11    13.1
3230         3230          NaN       120             16    14.4
3736         3736          NaN        41              8    14.8
4283         4283          NaN        77              7    14.4
4790         4790          NaN        91             16    14.5
38187       38183          NaN        39             12    20.9
40444       40440          NaN       120             16    14.8

In [67]:
df_prods.shape

(49693, 5)

In [68]:
df_prods_clean = df_prods[df_prods['product_name'].isnull() == False]

In [69]:
df_prods_clean.shape

(49677, 5)

Removed and filtered out missing values because product_name is a string value and string values cannot be imputted like numeric values.

In [70]:
#Step 7
#Run a check for duplicate values in your df_prods data.
df_dups = df_prods_clean[df_prods_clean.duplicated()]

In [71]:
df_dups

product_id                                       product_name  \
462           462                  Fiber 4g Gummy Dietary Supplement   
18459       18458                                         Ranger IPA   
26810       26808               Black House Coffee Roasty Stout Beer   
35309       35306  Gluten Free Organic Peanut Butter & Chocolate ...   
35495       35491                            Adore Forever Body Wash   

       aisle_id  department_id  prices  
462          70             11     4.8  
18459        27              5     9.2  
26810        27              5    13.4  
35309       121             14     6.8  
35495       127             11     9.9

In [72]:
df_prods_clean_no_dups = df_prods_clean.drop_duplicates()

In [73]:
df_prods_clean_no_dups.shape

(49672, 5)

5 duplicates were observed and then removed.

In [74]:
#Step 9
#Export df_prods_clean_no_dups as products_checked.csv
df_prods_clean_no_dups.to_csv(os.path.join(path, '02 Data','Prepared Data', 'prods_checked_clean.csv'))

# Orders Consistency Check

In [75]:
#Step 2
df_ords.describe()

Unnamed: 0      order_id       user_id  order_number  \
count  3.421083e+06  3.421083e+06  3.421083e+06  3.421083e+06   
mean   1.710541e+06  1.710542e+06  1.029782e+05  1.715486e+01   
std    9.875817e+05  9.875817e+05  5.953372e+04  1.773316e+01   
min    0.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
25%    8.552705e+05  8.552715e+05  5.139400e+04  5.000000e+00   
50%    1.710541e+06  1.710542e+06  1.026890e+05  1.100000e+01   
75%    2.565812e+06  2.565812e+06  1.543850e+05  2.300000e+01   
max    3.421082e+06  3.421083e+06  2.062090e+05  1.000000e+02   

       orders_day_of_week  order_hour_of_day  days_since_prior_order  
count        3.421083e+06       3.421083e+06            3.214874e+06  
mean         2.776219e+00       1.345202e+01            1.111484e+01  
std          2.046829e+00       4.226088e+00            9.206737e+00  
min          0.000000e+00       0.000000e+00            0.000000e+00  
25%          1.000000e+00       1.000000e+01            4.000000e+00  
50%          3.000000e+00       1.300000e+01            7.000000e+00  
75%          5.000000e+00       1.600000e+01            1.500000e+01  
max          6.000000e+00       2.300000e+01            3.000000e+01

My observations of the statistics are that they appear normal. There are 7 days of the week in the "orders_day_of_week" column which is consistent for dow and "order_hour_of_day" is consistent with how many hours there are in a day.

In [76]:
#step 3 and step 4
#Check for mixed-type data in df_ords
for col in df_ords.columns.tolist():
  weird = (df_ords[[col]].applymap(type) != df_ords[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_ords[weird]) > 0:
    print (col)

No mixed-type data in df_ords

In [77]:
#step 5
#Run a check for missing values in your df_ords dataframe.
df_ords.isnull().sum()

Unnamed: 0                     0
order_id                       0
user_id                        0
order_number                   0
orders_day_of_week             0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

days_since_prior_order has 206209 missing values

In [78]:
#Step 6
#Addressing the missing values
df_ords_nan = df_ords[df_ords['days_since_prior_order'].isnull()== True]

In [79]:
df_ords_nan

Unnamed: 0  order_id  user_id  order_number  orders_day_of_week  \
0                 0   2539329        1             1                   2   
11               11   2168274        2             1                   2   
26               26   1374495        3             1                   1   
39               39   3343014        4             1                   6   
45               45   2717275        5             1                   3   
...             ...       ...      ...           ...                 ...   
3420930     3420930    969311   206205             1                   4   
3420934     3420934   3189322   206206             1                   3   
3421002     3421002   2166133   206207             1                   6   
3421019     3421019   2227043   206208             1                   1   
3421069     3421069   3154581   206209             1                   3   

         order_hour_of_day  days_since_prior_order  
0                        8                     NaN  
11                      11                     NaN  
26                      14                     NaN  
39                      11                     NaN  
45                      12                     NaN  
...                    ...                     ...  
3420930                 12                     NaN  
3420934                 18                     NaN  
3421002                 19                     NaN  
3421019                 15                     NaN  
3421069                 11                     NaN  

[206209 rows x 7 columns]

The order number is 1 so it makes sense that there are no values for the days_since_prior_order column since this is the customer's 1st order. Once the user's place another order the days_since_prior_order column should show values instead of NaN. I chose to leave the dataset as it since it doesn't make sense to impute or remove/filter the data. The order number 1 can act as flag for a new customer.

In [80]:
#Step 7
#Run a check for duplicate values in your df_ords data.
df_ords_dups = df_ords[df_ords.duplicated()]

In [81]:
df_ords_dups

Empty DataFrame
Columns: [Unnamed: 0, order_id, user_id, order_number, orders_day_of_week, order_hour_of_day, days_since_prior_order]
Index: []

No duplicates found in df_ords

In [82]:
#Step 9
#Export df_prods_clean_no_dups as products_checked.csv
df_ords.to_csv(os.path.join(path, '02 Data','Prepared Data', 'orders_checked_clean.csv'))